from sqlalchemy.ext.asyncio import AsyncSession
from typing import List
from app.models.audit_log import AuditLog

async def log_decision(
    db: AsyncSession, 
    claim_id: int, 
    risk_score: float, 
    decision: str, 
    reasons: List[str]
) -> AuditLog:
    """
    Logs the final automated processing decision of a claim into the database.
    
    Inputs:
        db: Automatically injected Database AsyncSession
        claim_id: The ID of the processed claim
        risk_score: The final computed risk score
        decision: The decision state (e.g., APPROVE, REJECT, INVESTIGATE)
        reasons: A list of textual reasons generated by the rule engine 
                 (will be stored as JSONB in PostgreSQL)
                 
    Returns:
        The registered AuditLog database instance.
    """
    # Create the AuditLog model instance
    audit_log = AuditLog(
        claim_id=claim_id,
        risk_score=risk_score,
        decision=decision,
        reasons=reasons  # SQLAlchemy's JSONB natively converts Python lists perfectly!
    )
    
    # Add to session and save safely
    db.add(audit_log)
    await db.commit()
    
    # Retrieve the state to secure the auto-generated ID/created_at timestamp
    await db.refresh(audit_log)
    
    return audit_log
